project:
  name: quickstart-mongodb-atlas
  owner: quickstart-eng@amazon.com
tests:
  mdb-atlas-fargate:
    regions:
    - ap-south-1
    parameters:
      PublicKey: override
      PrivateKey: override
      OrgId: override
      ProjectName: tcat-project-$[taskcat_random-string]-$[taskcat_current_region]
      ClusterName: tcat-cluster-$[taskcat_random-string]-$[taskcat_current_region]
      DatabaseUserName: override
      DatabasePassword: override
      DatabaseUserRoleDatabaseName: admin
      ClusterRegion: AP_SOUTH_1
      AvailabilityZones: ap-south-1a,ap-south-1b
      PublicSubnet1CIDR: override
      PublicSubnet2CIDR: override
      VPCCIDR: 10.0.0.0/16
      QSS3BucketName: aws-quickstart
      QSS3BucketRegion: ap-south-1
      ClientServiceECRImageURI: override
      ServerServiceECRImageURI: override
      ActivateMongoDBResources: "No"
    template: quickstart_Fargate_V2.yaml
  mdb-atlas-fargate-2:
    regions:
    - eu-central-1
    parameters:
      PublicKey: override
      PrivateKey: override
      OrgId: override
      ProjectName: tcat-project-$[taskcat_random-string]-$[taskcat_current_region]
      ClusterName: tcat-cluster-$[taskcat_random-string]-$[taskcat_current_region]
      DatabaseUserName: override
      DatabasePassword: override
      DatabaseUserRoleDatabaseName: admin
      ClusterRegion: EU_CENTRAL_1
      AvailabilityZones: eu-central-1a,eu-central-1b
      PublicSubnet1CIDR: override
      PublicSubnet2CIDR: override
      VPCCIDR: 10.0.0.0/16
      QSS3BucketName: aws-quickstart
      QSS3BucketRegion: eu-central-1
      ClientServiceECRImageURI: override
      ServerServiceECRImageURI: override
      ActivateMongoDBResources: "No"
    template: quickstart_Fargate_V2.yaml
  mdb-atlas-fargate-3:
    regions:
    - us-east-1
    parameters:
      PublicKey: override
      PrivateKey: override
      OrgId: override
      ProjectName: tcat-project-$[taskcat_random-string]-$[taskcat_current_region]
      ClusterName: tcat-cluster-$[taskcat_random-string]-$[taskcat_current_region]
      DatabaseUserName: override
      DatabasePassword: override
      DatabaseUserRoleDatabaseName: admin
      ClusterRegion: US_EAST_1
      AvailabilityZones: us-east-1a,us-east-1b
      PublicSubnet1CIDR: override
      PublicSubnet2CIDR: override
      VPCCIDR: 10.0.0.0/16
      QSS3BucketName: aws-quickstart
      QSS3BucketRegion: us-east-1
      ClientServiceECRImageURI: override
      ServerServiceECRImageURI: override
      ActivateMongoDBResources: "No"
    template: quickstart_Fargate_V2.yaml