//Include any predeployment steps here, such as signing up for a Marketplace AMI or making any changes to a partner account. If there are no predeployment steps, leave this file empty.

== Predeployment steps

=== Prepare your AWS account

This Partner Solution uses MongoDB Atlas CloudFormation resource types and automatically registers them in the AWS Region of your choice. Once activated, you can safely skip this step for additional deployments in each Region by setting the `ActivateMongoDBResources` parameter to *No*.

=== Prepare your {partner-company-name} account

A MongoDB Atlas programmatic API key must be generated with the appropriate permissions and network access entries so that AWS CloudFormation can successfully authenticate the MongoDB cloud. For more information about creating and managing API keys, see https://docs.atlas.mongodb.com/tutorial/manage-programmatic-access[Programmatic Access to Atlas^].

After creating the programmatic API keys, they need to be stored in AWS Secrets Manager with Secret name pattern `cfn/atlas/profile/${ProfileName}`. Use https://github.com/mongodb/mongodbatlas-cloudformation-resources/blob/master/examples/profile-secret.yaml[this^] CloudFormation template to create the secret in the AWS region where this Partner solution is going to be deployed.

=== Create ECR Images for Client and Server Applications

Containerized applications for the Client and Server are required to be uploaded to ECR. For more details on creating container images please check the example code provided in this https://github.com/mongodb/mongodbatlas-cloudformation-resources/tree/master/quickstart-examples/fargate-example[GitHub repository^].
