//Include any predeployment steps here, such as signing up for a Marketplace AMI or making any changes to a partner account. If there are no predeployment steps, leave this file empty.

== Predeployment steps

=== Prepare your AWS account

This Partner Solution uses MongoDB Atlas CloudFormation resource types and automatically activates them in the AWS Region of your choice. Once it's running, you can safely skip this step for additional deployments in each Region by setting the `ActivateMongoDBResources` parameter to *No*.

=== Prepare your {partner-company-name} account

A MongoDB Atlas programmatic API key must be generated with the appropriate permissions and network access entries so AWS CloudFormation can successfully authenticate the MongoDB cloud. For more information about creating and managing API keys, refer to https://docs.atlas.mongodb.com/tutorial/manage-programmatic-access[Get Started with the Atlas Administration API^].

After creating the programmatic API key, store it as a secret in AWS Secrets Manager with the following naming convention: `cfn/atlas/profile/${ProfileName}`. Use this https://github.com/mongodb/mongodbatlas-cloudformation-resources/blob/master/examples/profile-secret.yaml[CloudFormation template^] to create the secret in the AWS Region where this Partner Solution will be deployed.

=== Create Amazon ECR images for client and server applications

Containerized applications for the client and server are required to be uploaded to Amazon ECR. For more details on creating container images see the example code provided in this https://github.com/mongodb/mongodbatlas-cloudformation-resources/tree/master/quickstart-examples/fargate-example[GitHub repository^].
