project:
  name: quickstart-mongodb-atlas
  owner: quickstart-eng@amazon.com
tests:
  mdb-atlas-fargate:
    regions:
    - us-east-1
    parameters:
      PublicKey: dllisqsk
      PrivateKey: 51768f23-0fb7-455d-9f03-4973b3413834
      OrgId: 5fe4ea50d1a2b617175ee3d4
      ProjectName: tcat-project-$[taskcat_random-string]-$[taskcat_current_region]
      ClusterName: tcat-cluster-$[taskcat_random-string]-$[taskcat_current_region]
      DatabaseUserName: testUser1
      DatabasePassword: test1231
      DatabaseUserRoleDatabaseName: admin
      ClusterRegion: US_EAST_1
      VpcId: vpc-07e2075326c2fe4df
    template: quickstart_Fargate_V2.yaml