project:
  name: quickstart-mongodb-atlas
  owner: quickstart-eng@amazon.com
tests:
  mdb-atlas-fargate:
    regions:
    - us-east-1
    parameters:
      PublicKey: override
      PrivateKey: override
      OrgId: override
      ProjectName: tcat-project-$[taskcat_random-string]-$[taskcat_current_region]
      ClusterName: tcat-cluster-$[taskcat_random-string]-$[taskcat_current_region]
      DatabaseUserName: override
      DatabasePassword: override
      DatabaseUserRoleDatabaseName: admin
      ClusterRegion: US_EAST_1
      VpcId: override
    template: quickstart_Fargate_V2.yaml