general:
  s3_regional_buckets: true
project:
  name: quickstart-mongodb-atlas
  owner: quickstart-eng@amazon.com
  # package_lambda: true
  # lambda_source_path: functions/source
  # lambda_zip_path: functions/packages
  # shorten_stack_name: true
tests:
  mdb-atlas-fargate:
    regions:
    - us-east-1
    parameters:
      PublicKey: override
      PrivateKey: override
      OrgId: override
      ProjectName: tcat-project-$[taskcat_random-string]-$[taskcat_current_region]
      ClusterName: tcat-cluster-$[taskcat_random-string]-$[taskcat_current_region]
      DatabaseUserName: override
      DatabasePassword: override
      DatabaseUserRoleDatabaseName: override
      ClusterRegion: override
      VpcId: override
    template: quickstart_Fargate_V2.yaml